ajustando andoird com o browserstack

diff --git a/.github/workflows/android_browserstack.yml b/.github/workflows/android_browserstack.yml
--- a/.github/workflows/android_browserstack.yml
+++ b/.github/workflows/android_browserstack.yml
@@ -1,4 +1,4 @@
-name: Android tests on BrowserStack
+name: iOS tests on BrowserStack
 
 on:
   push:
@@ -6,14 +6,14 @@ on:
   workflow_dispatch:
 
 jobs:
-  test-browserstack:
-    runs-on: ubuntu-latest
-    timeout-minutes: 30
+  test-browserstack-ios:
+    runs-on: macos-latest
+    timeout-minutes: 40
 
     env:
       BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
       BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
-      PLATFORM: android
+      PLATFORM: ios
 
     steps:
       - name: Checkout project
@@ -27,17 +27,17 @@ jobs:
       - name: Install dependencies
         run: npm ci
 
-      - name: Run tests on BrowserStack
-        run: npm run test:android
+      - name: Run iOS tests on BrowserStack
+        run: npx wdio run ./config/wdio.browserstack.conf.mjs
 
       - name: Generate Allure Report
         if: always()
-        run: npm run report
+        run: npm run report || echo "Allure report failed but tests already ran"
         continue-on-error: true
 
       - name: Upload Allure Report
         if: always()
         uses: actions/upload-artifact@v4
         with:
-          name: allure-report
+          name: allure-report-ios
           path: reports/allure-report
